---
homepage: https://github.com/kairichard/dotfiles/
version: 1.0
base: &basic
  - ackrc
  - bash
  - bash_profile
  - bashrc
  - tmux
  - tmux.conf
  - vim
  - vimrc

desktop: &desktop
  - gsdrc
  - xlock
  - config/**/*

vcs: &vcs
  - gitconfig
  - hgrc

ruby: &ruby
  - autotest
  - rspec
  - gemrc
  - irbrc
  - pryrc

vim_bundles: &vim_bundles
  - <%= @package_path/"bootstrap/vim/update_bundles.sh" %>

vim_ycm: &vim_ycm
  - <%= @package_path/"bootstrap/vim/ycm.sh" %>

osx: &osx
  config_files:
    - *basic
    - *desktop
    - *vcs
    - *ruby
    - iterm_server_profile_map

  setup:
    - <%= @package_path/"bootstrap/osx/brew" %>
    - <%= @package_path/"bootstrap/osx/defaults" %>
    - <%= @package_path/"bootstrap/osx/fonts" %>
    - *vim_bundles
    - *vim_ycm

  post:
    update:
      - *vim_bundles

ubuntu: &ubuntu
  config_files:
    - *basic
    - *vcs
    - *ruby

  setup:
    - <%= @package_path/"bootstrap/ubuntu/debian_pkgs.sh" %>
    - *vim_bundles
    - *vim_ycm

  post:
    update:
      - *vim_bundles

ubuntu-desktop: &ubuntu-desktop
  config_files:
    - *basic
    - *vcs
    - *ruby
    - *desktop

  setup:
    - <%= @package_path/"bootstrap/ubuntu/debian_pkgs.sh" %>
    - <%= @package_path/"bootstrap/ubuntu-desktop/debian_pkgs.sh" %>
    - *vim_bundles
    - *vim_ycm

  post:
    update:
      - *vim_bundles

flavors:
  osx: *osx
  ubuntu: *ubuntu
  ubuntu-desktop: *ubuntu-desktop
