---
homepage: https://github.com/kairichard/dotfiles/
version: 1.0
base: &basic
  - ackrc
  - ripgreprc
  - bash
  - bash_profile
  - bashrc
  - tmux.conf
  - vim
  - vimrc
  - gitmessage

desktop: &desktop
  - gsdrc
  - xlock
  - config/**/*
  - gnupg/**/*

vim_bundles: &vim_bundles
  - <%= @package_path/"bootstrap/vim/update_bundles.sh" %>

powerline: &powerline
  - <%= @package_path/"bootstrap/powerline/install.sh" %>

macos: &macos
  config_files:
    - *basic
    - *desktop

  setup:
    - <%= @package_path/"bootstrap/osx/brew" %>
    - <%= @package_path/"bootstrap/osx/fonts" %>
    - <%= @package_path/"bootstrap/cmd/tmux" %>
    - *powerline
    - *vim_bundles

  post:
    update:
      - *vim_bundles

flavors:
  macos: *macos
