#!/usr/bin/env bash

echo 'brewing our machine'
brew bundle ~/.bootstrap/osx/brewfile


function installcask() {
        brew cask install "${@}"
}

installcask imagealpha
installcask imageoptim
installcask iterm2
installcask macvim
installcask sequel-pro
installcask the-unarchiver
installcask virtualbox
installcask vlc
installcask atom
installcask google-drive
installcask apache-directory-studio
installcask skype
installcask microsoft-office
installcask microsoft-lync
installcask pycharm
installcask sizeup
installcask adobe-creative-cloud
installcask macpass
installcask dash
installcask spectacle
