#!/usr/bin/env bash

echo 'brewing our machine'
brew tap caskroom/cask
brew tap caskroom/fonts
# Make sure we’re using the latest Homebrew
brew update

# Upgrade any already-installed formulae
brew upgrade

# Install GNU core utilities (those that come with OS X are outdated)
# Don’t forget to add `$(brew --prefix coreutils)/libexec/gnubin` to `$PATH`.
brew install coreutils
brew install cmake
# Install GNU `find`, `locate`, `updatedb`, and `xargs`, g-prefixed
brew install findutils

brew install ack
brew install htop
brew install tmux
brew install python
brew install pyenv
brew install rbenv
brew install nodenv
brew install ruby-build
brew install autojump
brew install direnv
brew install ncmpcpp
brew install weechat --with-python --with-perl --with-ruby
brew install dos2unix
brew install homebrew/binary/kwm
brew install vim --with-python
brew install mawk
brew install openssh
brew install git
brew install bash-completion
brew install exa
brew install ripgrep
brew install hstr
brew install tldr
brew install xsv
brew install bat
brew install golang

# https://www.stevenrombauts.be/2018/01/use-dnsmasq-instead-of-etc-hosts/
brew install dnsmasq

# Fixes python pip
brew unlink python && brew link python

function installcask() {
        brew cask install "${@}"
}

installcask imagealpha
installcask imageoptim
installcask iterm2
installcask sequel-pro
installcask the-unarchiver
installcask virtualbox
installcask vlc
installcask google-backup-and-sync
installcask skype
if [[ "$CI" != "true" ]]; then installcask microsoft-office ; fi
installcask microsoft-teams
installcask pycharm
installcask webstorm
installcask whatsapp
installcask macpass
installcask spectacle
installcask alfred
installcask flux
installcask docker
installcask font-hack
installcask enpass
installcask spotify
installcask visual-studio-code
installcask slack
installcask firefox
installcask onedrive
installcask rcdefaultapp

echo "Installing others"
sudo pip install iterminator
